pipeline:
  name: pipeline_name
  identifier: pipeline_id
  projectIdentifier: project_id
  orgIdentifier: org_id
  tags: {}
  stages:
    - stage:
        name: DeployBG
        identifier: DeployBG
        description: ""
        type: Deployment
        spec:
          deploymentType: Asg
          service:
            serviceRef: your_service_ref
            serviceInputs:
              serviceDefinition:
                type: Asg
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: your_ami_artifact
          environment:
            environmentRef: your_environment_ref
            deployToAll: false
            infrastructureDefinitions:
              - identifier: your_infra_def
          execution:
            steps:
              - stepGroup:
                  name: Blue Green Deployment
                  identifier: blueGreenDeployment
                  steps:
                    - step:
                        name: Asg Blue Green Deploy
                        identifier: AsgBlueGreenDeploy
                        type: AsgBlueGreenDeploy
                        timeout: 15m
                        spec:
                          instances:
                            type: Fixed
                            spec:
                              min: 1
                              max: 1
                              desired: 1
                          loadBalancers:
                            - loadBalancer: asg-test
                              prodListener: your_listener_arn
                              prodListenerRuleArn: your_rule_arn
                    - step:
                        name: AsgShiftTraffic30
                        identifier: AsgShiftTraffic30
                        type: AsgShiftTraffic
                        timeout: 15m
                        spec:
                          weight: 30
                          downsizeOldAsg: false
                    - step:
                        name: AsgShiftTraffic100
                        identifier: AsgShiftTraffic100
                        type: AsgShiftTraffic
                        timeout: 15m
                        spec:
                          weight: 100
                          downsizeOldAsg: true
            rollbackSteps:
              - step:
                  name: Asg Blue Green Rollback
                  identifier: AsgBlueGreenRollback
                  type: AsgBlueGreenRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
